/**
 * Constants for JUSOR Admin Panel
 */

import type { SidebarGroup, PendingAction, ActivityItem, CampaignStatus, Performer, SystemHealth, QuickStat, Dispute, User, UserActivity } from '@/types';

export const SIDEBAR_GROUPS: SidebarGroup[] = [
  {
    label: 'OVERVIEW',
    items: [
      { id: 'dashboard', label: 'Dashboard', icon: 'grid' },
      { id: 'notifications', label: 'Notifications', icon: 'bell', count: 12, color: 'bg-violet-500' },
    ],
  },
  {
    label: 'MANAGEMENT',
    items: [
      { id: 'verification', label: 'Verification', icon: 'shield', count: 23, color: 'bg-rose-500' },
      { id: 'users', label: 'Users', icon: 'users' },
      { id: 'campaigns', label: 'Campaigns', icon: 'megaphone' },
    ],
  },
  {
    label: 'FINANCIAL',
    items: [
      { id: 'transactions', label: 'Transactions', icon: 'receipt' },
      { id: 'withdrawals', label: 'Withdrawals', icon: 'banknote', count: 8, color: 'bg-amber-500' },
    ],
  },
  {
    label: 'SUPPORT',
    items: [
      { id: 'disputes', label: 'Disputes', icon: 'scale', count: 5, color: 'bg-rose-500' },
      { id: 'content', label: 'Content Review', icon: 'fileCheck' },
    ],
  },
  {
    label: 'ANALYTICS',
    items: [{ id: 'reports', label: 'Reports', icon: 'chart' }],
  },
  {
    label: 'SETTINGS',
    items: [
      { id: 'platform', label: 'Platform Settings', icon: 'settings' },
      { id: 'security', label: 'Security', icon: 'shieldSimple' },
    ],
  },
];

export const PENDING_ACTIONS: PendingAction[] = [
  { label: 'Verification Requests', count: 23, icon: 'shield', color: 'bg-rose-500', urgent: true },
  { label: 'Pending Withdrawals', count: 8, icon: 'banknote', color: 'bg-amber-500', urgent: true },
  { label: 'Open Disputes', count: 5, icon: 'alert', color: 'bg-orange-500', urgent: true },
  { label: 'Content Reviews', count: 12, icon: 'fileCheck', color: 'bg-blue-500', urgent: false },
];

export const RECENT_ACTIVITIES: ActivityItem[] = [
  { type: 'verification', user: 'Noura Al-Rashid', action: 'submitted verification documents', time: '2 min ago', icon: 'shield', color: 'bg-blue-500' },
  { type: 'payment', user: 'TechStart Inc.', action: 'paid SAR 45,000 for campaign', time: '15 min ago', icon: 'banknote', color: 'bg-emerald-500' },
  { type: 'dispute', user: 'Fashion Brand Co.', action: 'opened a dispute on campaign #1247', time: '32 min ago', icon: 'alert', color: 'bg-rose-500' },
  { type: 'campaign', user: 'Ahmed Influencer', action: 'completed all deliverables for campaign #1243', time: '1 hr ago', icon: 'check', color: 'bg-emerald-500' },
  { type: 'withdrawal', user: 'Sara Content Creator', action: 'requested withdrawal of SAR 12,500', time: '2 hr ago', icon: 'wallet', color: 'bg-amber-500' },
  { type: 'verification', user: 'Gulf Retail LLC', action: 'business verification approved', time: '3 hr ago', icon: 'check', color: 'bg-emerald-500' },
];

export const CAMPAIGN_STATUSES: CampaignStatus[] = [
  { label: 'Active', count: 47, color: 'bg-emerald-500', width: '47%' },
  { label: 'Pending Payment', count: 12, color: 'bg-amber-500', width: '12%' },
  { label: 'In Review', count: 23, color: 'bg-blue-500', width: '23%' },
  { label: 'Completed', count: 156, color: 'bg-gray-400', width: '18%' },
];

export const TOP_PERFORMERS: Performer[] = [
  { name: 'Noura Al-Rashid', handle: '@noura_style', earnings: 'SAR 145,000', campaigns: 12, avatar: 'NR' },
  { name: 'Ahmed Al-Farsi', handle: '@ahmed_tech', earnings: 'SAR 98,500', campaigns: 8, avatar: 'AF' },
  { name: 'Sara Al-Mohammadi', handle: '@sara_beauty', earnings: 'SAR 87,200', campaigns: 15, avatar: 'SM' },
  { name: 'Khalid Al-Dosari', handle: '@khalid_vlogs', earnings: 'SAR 72,800', campaigns: 6, avatar: 'KD' },
];

export const SYSTEM_HEALTH: SystemHealth[] = [
  { name: 'API Response Time', value: '124ms', status: 'good' },
  { name: 'Database Load', value: '32%', status: 'good' },
  { name: 'Queue Processing', value: '0 pending', status: 'good' },
  { name: 'Payment Gateway', value: 'Online', status: 'good' },
  { name: 'SADQ Integration', value: 'Online', status: 'good' },
  { name: 'Nafath Service', value: 'Online', status: 'good' },
];

export const QUICK_STATS: QuickStat[] = [
  { label: 'Avg. Campaign Value', value: 'SAR 52,400', icon: 'dollarSign', change: '+12%', positive: true },
  { label: 'Completion Rate', value: '94.2%', icon: 'check', change: '+2.1%', positive: true },
  { label: 'Dispute Rate', value: '2.8%', icon: 'alert', change: '-0.4%', positive: true },
  { label: 'Avg. Review Time', value: '18 hrs', icon: 'clock', change: '-3 hrs', positive: true },
];

export const USER_GROWTH_DATA = {
  influencers: { total: 1847, new: 124, growth: '+8.2%' },
  businesses: { total: 423, new: 31, growth: '+5.4%' },
};

export const REVENUE_CHART_DATA = [45, 52, 38, 65, 42, 78, 55, 90, 72, 85, 68, 95, 88, 102];

export const DATE_RANGES = ['24h', '7d', '30d', '90d'] as const;

// Dispute Management
export const MOCK_DISPUTES: Dispute[] = [
  {
    id: 'DSP-1247',
    title: 'Content doesn\'t meet specifications',
    description: 'The delivered content does not include the required hashtags and product mentions as specified in the contract.',
    campaignId: 'CMP-2891',
    campaignName: 'Tech Product Launch',
    status: 'open',
    priority: 'high',
    type: 'content',
    createdAt: '2026-01-05T10:30:00',
    updatedAt: '2026-01-05T10:30:00',
    initiator: { id: 'BUS-5678', name: 'TechStart Inc.', type: 'business' },
    respondent: { id: 'INF-1234', name: 'Noura Al-Rashid', type: 'influencer', avatar: 'NR' },
    assignedAdmin: 'Ahmed Al-Qahtani',
    messages: [],
    evidence: [],
    amountInDispute: 45000,
  },
  {
    id: 'DSP-1245',
    title: 'Payment not received after approval',
    description: 'I completed the campaign and my content was approved on Dec 28. The payment should have been released within 48 hours.',
    campaignId: 'CMP-2698',
    campaignName: 'Summer Collection 2026',
    status: 'in_review',
    priority: 'high',
    type: 'payment',
    createdAt: '2026-01-03T09:15:00',
    updatedAt: '2026-01-05T14:20:00',
    initiator: { id: 'INF-3456', name: 'Fatima Al-Saud', type: 'influencer', avatar: 'FS' },
    respondent: { id: 'BUS-7890', name: 'Fashion House KSA', type: 'business' },
    assignedAdmin: 'Ahmed Al-Qahtani',
    messages: [],
    evidence: [],
    amountInDispute: 28000,
  },
  {
    id: 'DSP-1246',
    title: 'Post deleted prematurely',
    description: 'The influencer deleted the sponsored post after only 5 days. The contract clearly states the post must remain live for at least 30 days.',
    campaignId: 'CMP-2756',
    campaignName: 'Ramadan Special',
    status: 'open',
    priority: 'medium',
    type: 'contract',
    createdAt: '2026-01-04T14:20:00',
    updatedAt: '2026-01-04T14:20:00',
    initiator: { id: 'BUS-6789', name: 'Gulf Retail LLC', type: 'business' },
    respondent: { id: 'INF-2345', name: 'Ahmed Al-Farsi', type: 'influencer', avatar: 'AF' },
    assignedAdmin: 'Sara Al-Otaibi',
    messages: [],
    evidence: [],
    amountInDispute: 32000,
  },
  {
    id: 'DSP-1244',
    title: 'Quality below expectations',
    description: 'Video quality is lower than expected and some product features were not mentioned.',
    campaignId: 'CMP-2645',
    campaignName: 'New Year Promo',
    status: 'resolved',
    priority: 'low',
    type: 'content',
    createdAt: '2026-01-01T11:30:00',
    updatedAt: '2026-01-04T16:00:00',
    resolvedAt: '2026-01-04T16:00:00',
    initiator: { id: 'BUS-8901', name: 'Electronics Plus', type: 'business' },
    respondent: { id: 'INF-4567', name: 'Khalid Al-Mutairi', type: 'influencer', avatar: 'KM' },
    assignedAdmin: 'Ahmed Al-Qahtani',
    messages: [],
    evidence: [],
    amountInDispute: 15000,
    resolution: 'split',
    resolutionNote: 'Partial deliverables met. Split payment 70/30 in favor of influencer.',
  },
  {
    id: 'DSP-1243',
    title: 'Exclusivity violation',
    description: 'The influencer promoted a competing brand on the same day as our campaign launch, violating the 30-day exclusivity clause.',
    campaignId: 'CMP-2590',
    campaignName: 'Premium Brand Launch',
    status: 'open',
    priority: 'critical',
    type: 'contract',
    createdAt: '2025-12-28T08:00:00',
    updatedAt: '2026-01-05T09:00:00',
    initiator: { id: 'BUS-9012', name: 'Luxury Brands SA', type: 'business' },
    respondent: { id: 'INF-5678', name: 'Layla Al-Harbi', type: 'influencer', avatar: 'LH' },
    assignedAdmin: 'Mohammad Al-Dosari',
    messages: [],
    evidence: [],
    amountInDispute: 75000,
  },
];

// User Management
export const MOCK_USERS: User[] = [
  // Influencers
  {
    id: 'INF-1234',
    type: 'influencer',
    name: 'Noura Al-Rashid',
    nameAr: 'نورة الراشد',
    email: 'noura@email.com',
    phone: '+966 50 123 4567',
    avatar: 'NR',
    handle: '@noura_style',
    category: 'Fashion & Lifestyle',
    location: 'Riyadh',
    status: 'verified',
    joinedAt: '2025-10-15',
    lastActive: '2026-01-06T10:30:00',
    mawthooqId: '1098765432',
    falNumber: 'FL-2025-12345',
    iban: 'SA03 8000 0000 6080 1016 7519',
    ibanVerified: true,
    rating: 4.8,
    reviewCount: 24,
    followers: { instagram: 125000, tiktok: 89000, snapchat: 45000, youtube: 12000 },
    engagementRate: 4.2,
    totalCampaigns: 24,
    completedCampaigns: 22,
    activeCampaigns: 2,
    totalEarnings: 285000,
    pendingBalance: 45000,
    withdrawnAmount: 240000,
    disputeRate: 4.2,
    verificationDate: '2025-10-18',
    nafathVerified: true,
  },
  {
    id: 'INF-2345',
    type: 'influencer',
    name: 'Ahmed Al-Farsi',
    nameAr: 'أحمد الفارسي',
    email: 'ahmed.farsi@email.com',
    phone: '+966 55 234 5678',
    avatar: 'AF',
    handle: '@ahmed_lifestyle',
    category: 'Tech & Gaming',
    location: 'Jeddah',
    status: 'verified',
    joinedAt: '2025-08-20',
    lastActive: '2026-01-05T18:45:00',
    mawthooqId: '1087654321',
    falNumber: null,
    iban: 'SA44 1000 0000 0000 1234 5678',
    ibanVerified: true,
    rating: 4.5,
    reviewCount: 18,
    followers: { instagram: 78000, tiktok: 156000, youtube: 45000, twitter: 23000 },
    engagementRate: 5.1,
    totalCampaigns: 18,
    completedCampaigns: 17,
    activeCampaigns: 1,
    totalEarnings: 198000,
    pendingBalance: 28000,
    withdrawnAmount: 170000,
    disputeRate: 5.6,
    verificationDate: '2025-08-25',
    nafathVerified: true,
  },
  {
    id: 'INF-3456',
    type: 'influencer',
    name: 'Fatima Al-Saud',
    nameAr: 'فاطمة آل سعود',
    email: 'fatima.saud@email.com',
    phone: '+966 54 345 6789',
    avatar: 'FS',
    handle: '@fatima_beauty',
    category: 'Beauty & Skincare',
    location: 'Riyadh',
    status: 'pending',
    joinedAt: '2026-01-03',
    lastActive: '2026-01-06T09:15:00',
    mawthooqId: '1076543210',
    falNumber: null,
    iban: null,
    ibanVerified: false,
    rating: 0,
    reviewCount: 0,
    followers: { instagram: 52000, tiktok: 34000, snapchat: 28000 },
    engagementRate: 6.8,
    totalCampaigns: 0,
    completedCampaigns: 0,
    activeCampaigns: 0,
    totalEarnings: 0,
    pendingBalance: 0,
    withdrawnAmount: 0,
    disputeRate: 0,
    verificationDate: null,
    nafathVerified: true,
  },
  {
    id: 'INF-4567',
    type: 'influencer',
    name: 'Khalid Al-Mutairi',
    nameAr: 'خالد المطيري',
    email: 'khalid.reviews@email.com',
    phone: '+966 56 456 7890',
    avatar: 'KM',
    handle: '@khalid_reviews',
    category: 'Food & Travel',
    location: 'Dammam',
    status: 'suspended',
    joinedAt: '2025-06-10',
    lastActive: '2025-12-28T14:20:00',
    mawthooqId: '1065432109',
    falNumber: 'FL-2025-67890',
    iban: 'SA55 2000 0000 0000 5678 9012',
    ibanVerified: true,
    rating: 4.3,
    reviewCount: 12,
    followers: { instagram: 45000, youtube: 67000, snapchat: 23000 },
    engagementRate: 3.9,
    totalCampaigns: 12,
    completedCampaigns: 10,
    activeCampaigns: 0,
    totalEarnings: 95000,
    pendingBalance: 15000,
    withdrawnAmount: 80000,
    disputeRate: 16.7,
    verificationDate: '2025-06-15',
    nafathVerified: true,
    suspensionReason: 'Multiple contract violations - deleted posts before 90 days',
    suspendedAt: '2025-12-28',
  },
  // Businesses
  {
    id: 'BUS-5678',
    type: 'business',
    name: 'TechStart Inc.',
    nameAr: 'تك ستارت',
    email: 'marketing@techstart.sa',
    phone: '+966 11 234 5678',
    avatar: 'TS',
    category: 'Technology',
    location: 'Riyadh',
    status: 'verified',
    joinedAt: '2025-07-01',
    lastActive: '2026-01-06T11:00:00',
    crNumber: '1010567890',
    flNumber: null,
    wathiqVerified: true,
    rating: 4.6,
    reviewCount: 12,
    totalCampaigns: 12,
    completedCampaigns: 10,
    activeCampaigns: 2,
    totalSpent: 450000,
    currentEscrow: 95000,
    avgCampaignBudget: 37500,
    disputeRate: 8.3,
    verificationDate: '2025-07-05',
    contactPerson: 'Mohammed Al-Harbi',
    contactRole: 'Marketing Manager',
  },
  {
    id: 'BUS-6789',
    type: 'business',
    name: 'Gulf Retail LLC',
    nameAr: 'الخليج للتجزئة',
    email: 'campaigns@gulfretail.sa',
    phone: '+966 12 345 6789',
    avatar: 'GR',
    category: 'Retail & E-commerce',
    location: 'Jeddah',
    status: 'verified',
    joinedAt: '2025-09-15',
    lastActive: '2026-01-05T16:30:00',
    crNumber: '2020123456',
    flNumber: null,
    wathiqVerified: true,
    rating: 4.7,
    reviewCount: 8,
    totalCampaigns: 8,
    completedCampaigns: 7,
    activeCampaigns: 1,
    totalSpent: 320000,
    currentEscrow: 45000,
    avgCampaignBudget: 40000,
    disputeRate: 0,
    verificationDate: '2025-09-18',
    contactPerson: 'Sara Al-Otaibi',
    contactRole: 'Brand Director',
  },
  {
    id: 'BUS-7890',
    type: 'business',
    name: 'Luxury Brands SA',
    nameAr: 'العلامات الفاخرة',
    email: 'pr@luxurybrands.sa',
    phone: '+966 11 456 7890',
    avatar: 'LB',
    category: 'Luxury & Fashion',
    location: 'Riyadh',
    status: 'verified',
    joinedAt: '2025-05-20',
    lastActive: '2026-01-06T08:45:00',
    crNumber: '5050112233',
    flNumber: null,
    wathiqVerified: true,
    rating: 4.8,
    reviewCount: 28,
    totalCampaigns: 28,
    completedCampaigns: 26,
    activeCampaigns: 2,
    totalSpent: 1250000,
    currentEscrow: 150000,
    avgCampaignBudget: 44643,
    disputeRate: 3.6,
    verificationDate: '2025-05-25',
    contactPerson: 'Layla Al-Dosari',
    contactRole: 'CEO',
  },
  {
    id: 'BUS-8901',
    type: 'business',
    name: 'Fresh Bites Cafe',
    nameAr: 'فريش بايتس كافيه',
    email: 'hello@freshbites.sa',
    phone: '+966 55 567 8901',
    avatar: 'FB',
    category: 'Food & Beverage',
    location: 'Riyadh',
    status: 'pending',
    joinedAt: '2026-01-04',
    lastActive: '2026-01-05T12:00:00',
    crNumber: null,
    flNumber: 'FL-2026-11111',
    wathiqVerified: false,
    rating: 0,
    reviewCount: 0,
    totalCampaigns: 0,
    completedCampaigns: 0,
    activeCampaigns: 0,
    totalSpent: 0,
    currentEscrow: 0,
    avgCampaignBudget: 0,
    disputeRate: 0,
    verificationDate: null,
    contactPerson: 'Saleh Al-Qahtani',
    contactRole: 'Owner',
  },
];

// User Activity Log (for detail view)
export const MOCK_USER_ACTIVITY: UserActivity[] = [
  { id: 1, action: 'login', timestamp: '2026-01-06T10:30:00', details: 'Logged in from iPhone 15 Pro', ip: '192.168.1.1' },
  { id: 2, action: 'campaign_accepted', timestamp: '2026-01-05T14:20:00', details: 'Accepted invitation for CMP-2891', ip: '192.168.1.1' },
  { id: 3, action: 'content_submitted', timestamp: '2026-01-04T16:45:00', details: 'Submitted content for CMP-2845', ip: '192.168.1.2' },
  { id: 4, action: 'withdrawal', timestamp: '2026-01-03T11:00:00', details: 'Withdrew SAR 25,000 to IBAN ***7519', ip: '192.168.1.1' },
  { id: 5, action: 'profile_updated', timestamp: '2026-01-02T09:30:00', details: 'Updated bio and portfolio', ip: '192.168.1.1' },
  { id: 6, action: 'login', timestamp: '2026-01-01T18:15:00', details: 'Logged in from MacBook Pro', ip: '192.168.1.3' },
];
